/**
 * Created by dvorkin on 25.11.2016.
 */
public enum Zone {
    OUR_BASE,
    ENEMY_BASE,
    TOP_TURN,
    BOTTOM_TURN,
    CENTER,
    TOP_BEFORE_TURN,
    TOP_AFTER_TURN,
    BOTTOM_BEFORE_TURN,
    BOTTOM_AFTER_TURN,
    MIDDLE_BEFORE_CENTER,
    MIDDLE_AFTER_CENTER,
    TOP_BONUS,
    BOTTOM_BONUS,
    FOREST_OUR_TOP,
    FOREST_ENEMY_TOP,
    FOREST_OUR_BOTTOM,
    FOREST_ENEMY_BOTTOM
}
